const data = [
    {
        name:"LinkedIn",
        source:"https://jobbox-nextjs-v3.vercel.app/assets/imgs/brands/brand-1.png",
        location:"New York,US",
        position:"UI / UX Designer",
        description:"With supporting text below as a natural lead-in to additional content.",
        skills:["Adobe XD","Figma","Photoshop"],
        charges: "500",
    },{
        name:"Adobe Ilustrator",
        source:"https://jobbox-nextjs-v3.vercel.app/assets/imgs/brands/brand-2.png",
        location:"New York, US",
        position:"Full Stack Engineer",
        description:"With supporting text below as a natural lead-in to additional content.",
        skills:["React JS","Node JS"],
        charges: "800",
    },{
        name:"Bing Search",
        source:"https://jobbox-nextjs-v3.vercel.app/assets/imgs/brands/brand-3.png",
        location:"New York,US",
        position:"Java Software Engineer",
        description:"With supporting text below as a natural lead-in to additional content.",
        skills:["Python","AWS","Photoshop"],
        charges: "250",
    },{
        name:"Daily Motion",
        source:"https://jobbox-nextjs-v3.vercel.app/assets/imgs/brands/brand-4.png",
        location:"New York,US",
        position:"Frontend Developer",
        description:"With supporting text below as a natural lead-in to additional content.",
        skills:["TypeScript","Java"],
        charges: "250",
    },{
        name:"LinkedIn",
        source:"https://jobbox-nextjs-v3.vercel.app/assets/imgs/brands/brand-5.png",
        location:"New York,US",
        position:"React Native Web Developer",
        description:"With supporting text below as a natural lead-in to additional content.",
        skills:["Angular"],
        charges: "500",
    },{
        name:"Quora JSC",
        source:"https://jobbox-nextjs-v3.vercel.app/assets/imgs/brands/brand-6.png",
        location:"New York,US",
        position:"Senior System Engineer",
        description:"With supporting text below as a natural lead-in to additional content.",
        skills:["php","Android"],
        charges: "800",
    },{
        name:"Nintendo",
        source:"https://jobbox-nextjs-v3.vercel.app/assets/imgs/brands/brand-7.png",
        location:"New York,US",
        position:"Products Manager",
        description:"With supporting text below as a natural lead-in to additional content.",
        skills:["Asp.Net","Figma"],
        charges: "250",
    },{
        name:"Periscope",
        source:"https://jobbox-nextjs-v3.vercel.app/assets/imgs/brands/brand-8.png",
        location:"New York,US",
        position:"Lead Quality Control QA",
        description:"With supporting text below as a natural lead-in to additional content.",
        skills:["ios","Laravel","GoLang"],
        charges: "250",
    },
];